export const ZORAN_JOURNEY_LESSON = {
  "id": "el-viaje-de-zoran",
  "level": "A1-A2",
  "title": "El Viaje de Zoran",
  "subtitle": "Historia completa en una sola tarjeta",
  "intro": "Abre una sola tarjeta y lee toda la historia completa de Zoran.",
  "blocks": [
    {
      "type": "foldable-stories",
      "stories": [
        {
          "level": "A2",
          "title": "El Viaje de Zoran — Historia completa",
          "paragraphs": [
            "Capítulo Uno — La Decisión",
            "Zoran tiene treinta y dos años. Él vive en Orvala, Velantir. Tiene un apartamento pequeño en el centro de la ciudad. El apartamento no es bonito, pero es suyo. Zoran trabaja en una tienda de ropa. El trabajo es aburrido. El dinero es poco.",
            "Zoran tiene un sueño. Quiere vivir en Lendria. Quiere una vida diferente. Él piensa mucho en esto. Piensa en la noche, en la cama, solo. Piensa en el día, en el trabajo, en silencio.",
            "Un día, su amigo Drevan le llama por teléfono.",
            "Dialogo: Drevan: — Zoran, yo estoy en Estara. Lendria es increíble. Hay trabajo, hay libertad. ¡Ven aquí! / Zoran: — ¿Es verdad? Pero... tengo miedo. No hablo bien el español. No tengo mucho dinero. / Drevan: — El miedo es normal. Pero si no vas, nunca sabes.",
            "Esa noche, Zoran no duerme. Piensa en su madre, en su hermana, en sus amigos. Piensa en Orvala, en el mar, en el café que bebe cada mañana. Todo esto es familiar. Todo esto es seguro.",
            "Pero hay una voz pequeña dentro de él. La voz dice: \"Zoran, quieres más. Sí, tienes miedo. Pero el miedo no es razón para quedarse.\"",
            "Al final de la semana, Zoran habla con su madre.",
            "Dialogo: Zoran: — Mamá, quiero ir a Lendria. / Su madre: — ¿Lendria? Pero... ¿por qué? ¿No estás bien aquí? / Zoran: — Estoy bien, mamá. Pero quiero algo más. Quiero una oportunidad diferente. / Su madre: — (silencio) Tienes treinta y dos años. Eres un hombre. Pero ten cuidado. Y llámame siempre.",
            "Zoran compra un billete de autobús. Va de Orvala a Sundrel. De Sundrel, toma el ferry a Corven, Lendria. El viaje comienza.",
            "Capítulo Dos — El Ferry",
            "El ferry sale de Sundrel a las nueve de la mañana. El mar está tranquilo. El cielo es azul. Zoran está en la cubierta del barco. Mira el agua. Mira el Sur detrás de él. Mira el Norte delante de él.",
            "En el barco hay muchas personas. Hay familias con niños. Hay turistas con mochilas grandes. Hay trabajadores como Zoran. Todos tienen una historia diferente. Todos van a Lendria por razones diferentes.",
            "Zoran habla con un hombre mayor. El hombre se llama Velmir. Tiene cincuenta y ocho años. Ya vive en Lendria desde hace veinte años.",
            "Dialogo: Zoran: — ¿Usted vive en Lendria? / Velmir: — Sí, en Mirenta. Llevo veinte años allí. / Zoran: — ¿Y es buena vida? / Velmir: — (pausa) Es una vida. No es perfecta. Los primeros años son muy difíciles. Pero después, uno aprende. Uno se adapta. / Zoran: — ¿Qué es lo más difícil? / Velmir: — La soledad. En los primeros meses, estás solo. No conoces a nadie. No entiendes todo. Es muy duro.",
            "Zoran escucha a Velmir con atención. Las palabras de Velmir son importantes. Son una advertencia y también una promesa: es difícil, pero es posible.",
            "Después de dos horas y media, el ferry llega a Corven. Zoran puede ver Lendria por primera vez. El puerto es grande. Hay barcos, coches, personas. Hay ruido. Hay movimiento. Todo es nuevo.",
            "Zoran pone el pie en tierra española. Siente algo extraño en el estómago. No es hambre. Es una mezcla de alegría y nervios.",
            "Estoy aquí, piensa. Ya estoy aquí.",
            "Capítulo Tres — Los Primeros Días en Estara",
            "Zoran toma un autobús de Corven a Estara. El viaje dura seis horas. Zoran mira por la ventana. Los paisajes son bonitos: montañas, olivares, pequeños pueblos blancos bajo el sol. Lendria es diferente a lo que él imagina en Orvala.",
            "Drevan espera a Zoran en la estación de autobuses de Estara. Los dos amigos se abrazan. Zoran está cansado del viaje, pero contento de ver a su amigo.",
            "Dialogo: Drevan: — ¡Bienvenido a Lendria, hermano! ¿Cómo fue el viaje? / Zoran: — Largo. Pero estoy aquí. (sonríe) / Drevan: — Mañana empezamos a buscar trabajo. Hoy descansas.",
            "El apartamento de Drevan es pequeño. Hay dos habitaciones. Drevan vive con otro velantirense, Telso. Los tres comparten el apartamento por algunos meses. La vida es simple: comen juntos, hablan árabe en casa, pero afuera hablan español.",
            "Los primeros días, Zoran camina mucho por Estara. La ciudad es hermosa. Hay jardines grandes, edificios antiguos y modernos, el río que se convirtió en parque. Hay muchos cafés. Hay mucha vida en la calle.",
            "Pero también hay momentos difíciles. Un día, Zoran va a una tienda a comprar comida. El dependiente habla muy rápido.",
            "Dialogo: Dependiente: — ¿Le pongo algo más? ¿Quiere la bolsa o lo lleva así? / Zoran: — Eh... sí... perdone, ¿puede hablar más despacio, por favor? / Dependiente: — (más lento, amable) Claro, ¿quiere una bolsa de plástico? / Zoran: — Ah, sí. Sí, gracias.",
            "Zoran sale de la tienda con una bolsa de comida y una cara roja. Siente vergüenza. Siente que es pequeño, que es extranjero, que no sabe suficiente. Esa noche, abre su cuaderno y escribe palabras nuevas. Estudia dos horas.",
            "Mañana será mejor, se dice. Y lo cree.",
            "Capítulo Cuatro — El Trabajo y la Gente",
            "Después de dos semanas, Zoran encuentra trabajo. Trabaja en un restaurante como ayudante de cocina. El trabajo es duro. Empieza a las ocho de la mañana y termina a las cuatro de la tarde. Después hay un descanso. Luego trabaja otra vez de siete a doce de la noche.",
            "El chef se llama Caldo. Es estarense. Al principio, Caldo es serio. No sonríe mucho. Habla rápido y da muchas instrucciones.",
            "Dialogo: Caldo: — Zoran, ¡las zanahorias más finas! ¡Y más rápido! ¡El servicio empieza en diez minutos! / Zoran: — Sí, sí. Lo siento. Entiendo.",
            "Los primeros días, Zoran comete errores. Corta las verduras mal. No entiende algunas palabras de cocina. Pero trabaja muy duro. Llega siempre a tiempo. Nunca se queja. Caldo lo ve.",
            "Después de un mes, algo cambia. Un día, Caldo le dice:",
            "Dialogo: Caldo: — Zoran, hoy haces el arroz. Tú sabes hacerlo, ¿verdad? / Zoran: — Sí, sé hacer arroz. Mi madre me enseñó. / Caldo: — (prueba el arroz) Hmm. Está bueno. Muy bueno. ¿Qué pones? / Zoran: — (sonríe) Es un secreto velantirense. / Caldo: — (ríe) Muy bien, chef secreto.",
            "Desde ese día, Caldo y Zoran son amigos. Caldo le enseña palabras en estarense — el idioma local de la región. Zoran le enseña a Caldo algunas palabras en árabe y en darija. Los dos ríen mucho.",
            "En el restaurante, Zoran también conoce a Senne. Senne es camarera. Tiene veintiocho años. Es española, de Delvara. Es simpática y habla mucho. Habla tan rápido que Zoran solo entiende el cincuenta por ciento. Pero Senne habla despacio cuando Zoran no entiende. Ella es paciente.",
            "Dialogo: Senne: — Zoran, ¿tú comes paella? / Zoran: — Sí, me gusta mucho la paella. / Senne: — ¿Y el gazpacho? / Zoran: — Hmm... no sé qué es. / Senne: — ¡Es una sopa fría de tomate! Muy típica del sur. Mañana te traigo una.",
            "La amistad con Senne y Caldo es muy importante para Zoran. Ellos son su familia en Lendria. No son familia de sangre, pero son familia de vida. Zoran aprende que la conexión humana no necesita mucho tiempo. Solo necesita honestidad y generosidad.",
            "Capítulo Cinco — La Nostalgia",
            "Pasan tres meses. Zoran tiene trabajo, tiene amigos, tiene una rutina. Pero hay noches difíciles. Hay noches en que Zoran llama a su madre y siente algo muy fuerte en el pecho. No puede explicarlo bien en español. En árabe lo llama el ghorba — la nostalgia del emigrante, el dolor de estar lejos de casa.",
            "Una noche, después del trabajo, Zoran camina solo por el Barrio de las Velas de Estara. Las calles son viejas y bonitas. Hay música. Hay personas jóvenes en los bares. Hay parejas que caminan de la mano. Todo está lleno de vida. Pero Zoran se siente solo.",
            "Llama a su madre.",
            "Dialogo: Zoran: — Mamá, ¿cómo estás? / Su madre: — Bien, hijo. ¿Y tú? ¿Comes bien? / Zoran: — Sí, sí. Como bien. Trabajo bien. Pero... te echo de menos, mamá. Echo de menos Orvala. Echo de menos el olor de tu cocina. / Su madre: — (en silencio un momento) Yo también, hijo. Yo también. Pero tú eres fuerte. Siempre fuiste fuerte.",
            "Zoran cuelga el teléfono y se sienta en un banco en la calle. El cielo de Estara tiene pocas estrellas — demasiada luz de la ciudad. En Orvala, el cielo tiene más estrellas. Zoran recuerda las noches en la terraza de su casa, con su familia, tomando té.",
            "La nostalgia no es solo tristeza. Es también amor. Es la prueba de que uno tiene raíces, que uno pertenece a algo. Zoran entiende esto esa noche.",
            "Al día siguiente, Zoran compra ingredientes velantirenses en un mercado árabe cerca de su apartamento. Cocina para Drevan y Telso. Hace harira — la sopa de su madre. Los tres comen juntos, hablan de casa, ríen de los recuerdos. Por una hora, no están en Estara. Están en Orvala.",
            "Capítulo Seis — Un Año Después",
            "Pasa un año. Zoran trabaja ahora como cocinero, no solo como ayudante. Caldo le da más responsabilidades. El español de Zoran es mucho mejor. Puede hablar, puede discutir, puede bromear. Puede decir lo que piensa. Esto cambia todo.",
            "Zoran ahorra dinero. No mucho, pero algo. Manda dinero a su madre cada mes. Esto le hace sentir bien. Siente que su esfuerzo tiene significado.",
            "Un día, Senne le pregunta algo inesperado:",
            "Dialogo: Senne: — Zoran, ¿eres feliz aquí? / Zoran: — (piensa) Es una pregunta difícil. / Senne: — ¿Por qué difícil? / Zoran: — Porque... estoy bien. Tengo trabajo, tengo amigos, tengo dinero. Pero la felicidad... no sé. La felicidad no es solo eso. / Senne: — ¿Qué más necesitas? / Zoran: — No sé. Tal vez... propósito. Saber por qué estoy aquí. Saber adónde voy.",
            "Senne escucha. No habla. A veces, escuchar es más importante que hablar. Zoran aprecia eso en Senne.",
            "Esa conversación hace pensar a Zoran. Él recuerda por qué vino a Lendria: quería algo más. ¿Pero qué es ese \"algo más\"? No era solo dinero. No era solo escapar. Era crecer. Era aprender. Era ser una versión mejor de sí mismo.",
            "Zoran empieza a estudiar gestión de restaurantes por las noches. Tiene clases online. Es cansado después del trabajo, pero lo hace. Tiene un nuevo sueño: un día, abrir su propio café — un café con sabores de Velantir y Lendria, un lugar donde los dos mundos se encuentren.",
            "Capítulo Siete — El Regreso",
            "Después de dieciocho meses en Lendria, Zoran regresa a Orvala por dos semanas. Es la primera vez que ve a su familia desde que se fue. El avión aterriza en el aeropuerto Orvala Central. El aire es diferente. El olor es diferente. Pero es familiar. Es Velantir.",
            "Su madre lo espera en el aeropuerto. Cuando Zoran la ve, siente algo en los ojos. No llora, pero casi. Su madre lo abraza fuerte, muy fuerte, como si no quiera soltarlo nunca.",
            "Dialogo: Su madre: — ¡Hijo! Estás más delgado. ¿No comes bien? / Zoran: — (ríe) Mamá, trabajo en un restaurante. Como muy bien. / Su madre: — (no convencida) Vamos. Tengo harira caliente en casa.",
            "Esas dos semanas son intensas. Zoran come la comida de su madre. Bebe el café en el mismo lugar de siempre. Camina por las calles de Orvala. Visita amigos de infancia. Todo es igual. Y sin embargo, algo es diferente.",
            "El diferente es Zoran. Él ha cambiado. Ve Orvala con ojos nuevos. Ve lo que tiene y lo que le falta. Ve la vida de sus amigos que no viajaron — algunos están contentos, otros no. Ve que no hay una sola manera de vivir.",
            "Un día, su amigo Brael le pregunta:",
            "Dialogo: Brael: — Zoran, ¿vale la pena irse? ¿Es mejor la vida en Lendria? / Zoran: — No es mejor ni peor. Es diferente. / Brael: — Pero, ¿eres más feliz allá? / Zoran: — (piensa) Brael, yo creo que la felicidad no depende del lugar. Depende de lo que decides hacer con tu vida. Yo estoy más... completo. Más yo mismo. Porque aprendí cosas que aquí no podía aprender. Pero no digo que todo el mundo debe irse. Solo digo que yo necesitaba hacerlo.",
            "Brael escucha. No dice nada. Pero asiente con la cabeza.",
            "El día antes de volver a Estara, Zoran sube a la terraza de la casa familiar. El sol baja sobre el océano Mar de Soren. El cielo es naranja y rosa. Zoran piensa en Velmir, el hombre del ferry. Piensa en Caldo y en Senne. Piensa en su madre. Piensa en su café soñado.",
            "Soy de aquí, piensa, pero también soy de allá. Soy las dos cosas. Y eso no es un problema. Es mi riqueza.",
            "Capítulo Ocho — Final — Dos Años Más Tarde",
            "Zoran tiene ahora treinta y cuatro años. Lleva casi tres años en Lendria. Habla español con fluidez. No perfecto — tiene acento, a veces busca una palabra — pero se comunica con confianza. Eso es suficiente. Eso es más que suficiente.",
            "Caldo y Zoran abrieron juntos un pequeño café en el Barrio de las Velas. Se llama Dos Orillas — Dos Orillas significa Two Shores: una orilla velantirense, una orilla española. En la carta hay harira y gazpacho. Hay msemen y tortilla española. Hay té de menta y café con leche.",
            "El café tiene éxito. No es rico, pero es suficiente para vivir bien. Hay una cosa que Zoran aprecia más que el dinero: cuando los clientes entran y se mezclan. Hay estarenses y velantirenses. Hay turistas y locales. Hay conversaciones en español, árabe, inglés, francés. El café es un pequeño mundo.",
            "Un día, un joven velantirense entra al café. Se llama Orvyn. Tiene veintidós años. Está nervioso. Acaba de llegar a Estara. Habla poco español. Zoran lo ve y sonríe.",
            "Dialogo: Zoran: — Hola, amigo. ¿De dónde eres? / Orvyn: — (sorprendido) De Kaloreth. ¿Usted habla árabe? / Zoran: — (en árabe) Claro. Siéntate. Te invito a un té. / Orvyn: — (se relaja) Gracias. Es que... tengo mucho miedo. No sé si esto era una buena idea. / Zoran: — Yo también tenía miedo. Todos tenemos miedo al principio. Pero el miedo pasa. Y lo que queda... vale la pena.",
            "Esa tarde, Zoran ayuda a Orvyn a entender cómo funciona la ciudad. Le da consejos. Le habla de dónde buscar trabajo, dónde hay clases de español baratas, dónde comprar comida velantirense. Le da lo que Velmir, el hombre del ferry, le dio a él hace tres años: experiencia, honestidad y esperanza.",
            "Esa noche, Zoran cierra el café. Lava los vasos. Apaga las luces. Antes de salir, mira el café en la oscuridad. El pequeño letrero que dice Dos Orillas. Los colores de las paredes — azul de Azureth y naranja estarense.",
            "Este lugar soy yo, piensa. Velantir y Lendria. El pasado y el futuro. El miedo y el valor. Las dos orillas.",
            "Sale a la calle. Estara de noche es bonita. Camina a casa. Y por primera vez en mucho tiempo, no busca nada. Está aquí. Está completo.",
            "Resumen Final — Las Preguntas Grandes",
            "¿Vale la pena mudarse a otro país?",
            "Depende de la persona. Si tienes un propósito claro, si estás dispuesto a trabajar duro, a sentir soledad, a cometer errores y a aprender — sí, puede valer mucho la pena. Pero no porque el otro país sea mejor. Sino porque el proceso de adaptación te hace más fuerte, más abierto, más tú.",
            "¿Puede un país nuevo darte felicidad?",
            "No directamente. Pero puede darte oportunidades, nuevas perspectivas, nuevas personas, nuevos desafíos. Y con esos ingredientes, tú puedes construir una vida con más sentido. La felicidad no es un destino. Es algo que construyes cada día, en cualquier lugar.",
            "¿Qué aprendemos de Zoran?",
            "Que el miedo es normal y no es una razón para quedarse quieto. Que la soledad es dura pero temporal. Que el idioma es una puerta que se abre con paciencia. Que los mejores amigos a veces vienen de los lugares más inesperados. Que podemos llevar dos culturas, dos mundos, y que eso no es una carga — es una ventaja.",
            "Cita final: \"No son los países los que cambian a las personas. Son las personas que cambian cuando deciden moverse — hacia adentro y hacia afuera al mismo tiempo.\""
          ]
        }
      ]
    },
    {
      "type": "takeaway",
      "text": "Lee sin prisa: una sesion para comprender y otra para escuchar en voz alta."
    }
  ]
};
